export const data = [
  {
    code: 1000,
    day: "Sunny",
    night: "Clear",
    icon: 113,
    day_link: "/animated/day.svg",
    night_link: "/animated/night.svg",
  },
  {
    code: 1003,
    day: "Partly cloudy",
    night: "Partly cloudy",
    icon: 116,
    day_link: "/animated/cloudy-day-1.svg",
    night_link: "/animated/cloudy-night-1.svg",
  },
  {
    code: 1006,
    day: "Cloudy",
    night: "Cloudy",
    icon: 119,
    day_link: "/animated/cloudy.svg",
    night_link: "/animated/cloudy.svg",
  },
  {
    code: 1009,
    day: "Overcast",
    night: "Overcast",
    icon: 122,
    day_link: "/animated/cloudy-day-3.svg",
    night_link: "/animated/cloudy-night-3.svg",
  },

  {
    code: 1063,
    day: "Patchy rain possible",
    night: "Patchy rain possible",
    icon: 176,
    day_link: "/animated/rainy-2.svg",
    night_link: "/animated/rainy-4.svg",
  },
  {
    code: 1066,
    day: "Patchy snow possible",
    night: "Patchy snow possible",
    icon: 179,
    day_link: "/animated/",
    night_link: "/animated/",
  },
  {
    code: 1069,
    day: "Patchy sleet possible",
    night: "Patchy sleet possible",
    icon: 182,
    day_link: "/animated/snowy-2.svg",
    night_link: "/animated/snowy-4.svg",
  },
  {
    code: 1072,
    day: "Patchy freezing drizzle possible",
    night: "Patchy freezing drizzle possible",
    icon: 185,
    day_link: "/animated/snowy-3.svg",
    night_link: "/animated/snowy-5.svg",
  },
  {
    code: 1087,
    day: "Thundery outbreaks possible",
    night: "Thundery outbreaks possible",
    icon: 200,
    day_link: "/animated/thunder.svg",
    night_link: "/animated/thunder.svg",
  },
  {
    code: 1114,
    day: "Blowing snow",
    night: "Blowing snow",
    icon: 227,
    day_link: "/animated/snowy-7.svg",
    night_link: "/animated/snowy-7.svg",
  },
  {
    code: 1117,
    day: "Blizzard",
    night: "Blizzard",
    icon: 230,
    day_link: "/animated/snowy-7.svg",
    night_link: "/animated/snowy-7.svg",
  },

  {
    code: 1150,
    day: "Patchy light drizzle",
    night: "Patchy light drizzle",
    icon: 263,
    day_link: "/animated/rainy-2.svg",
    night_link: "/animated/rainy-4.svg",
  },
  {
    code: 1153,
    day: "Light drizzle",
    night: "Light drizzle",
    icon: 266,
    day_link: "/animated/rainy-4.svg",
    night_link: "/animated/rainy-4.svg",
  },

  {
    code: 1180,
    day: "Patchy light rain",
    night: "Patchy light rain",
    icon: 293,
    day_link: "/animated/rainy-4.svg",
    night_link: "/animated/rainy-4.svg",
  },
  {
    code: 1183,
    day: "Light rain",
    night: "Light rain",
    icon: 296,
    day_link: "/animated/rainy-3.svg",
    night_link: "/animated/rainy-5.svg",
  },
  {
    code: 1186,
    day: "Moderate rain at times",
    night: "Moderate rain at times",
    icon: 299,
    day_link: "/animated/rainy-3.svg",
    night_link: "/animated/rainy-5.svg",
  },
  {
    code: 1189,
    day: "Moderate rain",
    night: "Moderate rain",
    icon: 302,
    day_link: "/animated/rainy-7.svg",
    night_link: "/animated/rainy-7.svg",
  },
  {
    code: 1192,
    day: "Heavy rain at times",
    night: "Heavy rain at times",
    icon: 305,
    day_link: "/animated/rainy-6.svg",
    night_link: "/animated/rainy-6.svg",
  },
  {
    code: 1195,
    day: "Heavy rain",
    night: "Heavy rain",
    icon: 308,
    day_link: "/animated/rainy-6.svg",
    night_link: "/animated/rainy-6.svg",
  },
  {
    code: 1210,
    day: "Patchy light snow",
    night: "Patchy light snow",
    icon: 323,
    day_link: "/animated/snowy-2.svg",
    night_link: "/animated/snowy-4.svg",
  },
  {
    code: 1213,
    day: "Light snow",
    night: "Light snow",
    icon: 326,
    day_link: "/animated/snowy-2.svg",
    night_link: "/animated/snowy-4.svg",
  },
  {
    code: 1216,
    day: "Patchy moderate snow",
    night: "Patchy moderate snow",
    icon: 329,
    day_link: "/animated/snowy-3.svg",
    night_link: "/animated/snowy-5.svg",
  },
  {
    code: 1219,
    day: "Moderate snow",
    night: "Moderate snow",
    icon: 332,
    day_link: "/animated/snowy-3.svg",
    night_link: "/animated/snowy-5.svg",
  },
  {
    code: 1222,
    day: "Patchy heavy snow",
    night: "Patchy heavy snow",
    icon: 335,
    day_link: "/animated/snowy-6.svg",
    night_link: "/animated/snowy-6.svg",
  },
  {
    code: 1225,
    day: "Heavy snow",
    night: "Heavy snow",
    icon: 338,
    day_link: "/animated/snowy-6.svg",
    night_link: "/animated/snowy-6.svg",
  },
  {
    code: 1240,
    day: "Light rain shower",
    night: "Light rain shower",
    icon: 353,
    day_link: "/animated/rainy-2.svg",
    night_link: "/animated/rainy-4.svg",
  },
  {
    code: 1243,
    day: "Moderate or heavy rain shower",
    night: "Moderate or heavy rain shower",
    icon: 356,
    day_link: "/animated/rainy-6.svg",
    night_link: "/animated/rainy-6.svg",
  },
  {
    code: 1246,
    day: "Torrential rain shower",
    night: "Torrential rain shower",
    icon: 359,
    day_link: "/animated/rainy-6.svg",
    night_link: "/animated/rainy-6.svg",
  },
  {
    code: 1276,
    day: "Moderate or heavy rain with thunder",
    night: "Moderate or heavy rain with thunder",
    icon: 389,
    day_link: "/animated/thunder.svg",
    night_link: "/animated/thunder.svg",
  },
];
